[base]
engine = "docker"
path = "{{PWD}}"
output = "output"
logs = "logs"
data_path = "{{MAPYDE_DATA}}"
cards_path = "{{MAPYDE_CARDS}}"
scripts_path = "{{MAPYDE_SCRIPTS}}"
process_path = "{{MAPYDE_CARDS}}/process/"
param_path = "{{MAPYDE_CARDS}}/param/"
run_path = "{{MAPYDE_CARDS}}/run/"
pythia_path = "{{MAPYDE_CARDS}}/pythia/"
delphes_path = "{{MAPYDE_CARDS}}/delphes/"
madspin_path = "{{MAPYDE_CARDS}}/madspin/"
likelihoods_path = "{{MAPYDE_LIKELIHOODS}}"

[madgraph]
skip = false
params = "Higgsino"
ecms = 13000
cores = 20
nevents = 10000
seed = 0
version = "madgraph"
batch = false
paramcard = "{{madgraph['params']}}.slha"

[madgraph.generator]
output = "run.mg5"

[madgraph.masses]
MN1 = 100
MC1 = 150

[madgraph.run]
card = "default_LO.dat"

[madgraph.run.options]
mmjj = 0
mmjjmax = -1
deltaeta = 0
ktdurham = -1
xqcut = -1
ptj = 20
ptj1min = 0

[madgraph.proc]
name = "VBFSUSY_EWKQCD"
card = "{{madgraph['proc']['name']}}"

[madspin]
skip = true
card = ''

[sherpa]
proc="tt"
nevents = 2
cores = 1

[pythia]
skip = false
card = "pythia8_card.dat"
additional_opts = ""

[delphes]
skip = false
additional_opts = ""
card = "delphes_card_ATLAS.tcl"
version = "delphes"
output = "delphes/delphes.root"

[analysis]
script = "Delphes2SA.py"
XSoverride = -1
kfactor = -1
output = "analysis/Delphes2SA.root"
lumi = 1000

[simpleanalysis]
skip = false
additional_opts = ""
name = "EwkCompressed2018"

[sa2json]
inputs = "{{simpleanalysis['name']}}.root"
image = "pyplotting:latest"
output = "{{simpleanalysis['name']}}_patch.json"
options = ""

[pyhf]
skip = true
likelihood = "Higgsino_2L_bkgonly.json"
image = "pyplotting:latest"
gpu-options = "-c"

[root2hdf5]
input = "analysis/lowlevelAna.root"
treename = "allev/lowleveltree"
