[base]
output = "githubci"

[madgraph]
cores = 1

[madgraph.run]
ecms = 100000
nevents = 1000

[madgraph.proc]
name = "charginos"

[madgraph.masses]
MN1 = 150.0
MN2 = 155.0
MC1 = 155.0

[pythia]
mpi="off"
