name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all-files

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv pip install --system hatch 'click < 8.3.0'

      - name: Run PyLint
        run: |
          echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
          hatch run lint

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.13"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

        include:
          - python-version: pypy3.9
            runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv pip install --system hatch 'click < 8.3.0'

      - name: Test package
        run: hatch run +py=${{ matrix.python-version}} dev:test

  dist:
    name: Distribution build
    runs-on: ubuntu-latest
    needs: [pre-commit]
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv pip install --system hatch 'click < 8.3.0'

      - name: Build sdist and wheel; and check products
        run: hatch run build-check

      - uses: actions/upload-artifact@v4
        with:
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        if:
          github.event_name == 'release' && github.event.action == 'published'
          && github.repository == 'scipp-atlas/mapyde'
